### ISSUE TITLE
Cannot find module webpack-watch-time-plugin

### ISSUE THREAD

**Issue by ElviraCB** [sca-/webpack-watch-time-plugin#1]
Hello,

I've installed the plugin via the command: **npm install --save webpack-watch-time-plugin**
I can see the plugin in my node_modules folder.

I get the following error:

Error: Cannot find module 'webpack-watch-time-plugin'
cb-search_searchkit |     at Function.Module._resolveFilename (module.js:547:15)
cb-search_searchkit |     at Function.Module._load (module.js:474:25)
cb-search_searchkit |     at Module.require (module.js:596:17)
cb-search_searchkit |     at require (internal/module.js:11:18)
cb-search_searchkit |     at Object.<anonymous> (/usr/src/app/webpack.config.js:6:25)

This is my webpack config:
```
// webpack.config.js
const webpack = require("webpack");
const path = require("path");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const WatchTimePlugin = require("webpack-watch-time-plugin");

const config = {
  context: path.resolve(__dirname, "src"),
  entry: "./app.js",
  devServer: {
    contentBase: "./dist"
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js"
  },
  resolve: {
    // Add '.ts' and '.tsx' as resolvable extensions.
    extensions: [".ts", ".tsx", ".js", ".json"]
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: path.resolve(__dirname, "src"),
        use: [
          {
            loader: "babel-loader",
            options: {
              presets: [["env", { modules: false }], "react"]
            }
          }
        ]
      },
      {
        test: /\.tsx?$/,
        loader: "awesome-typescript-loader"
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract("css-loader")
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV),
      "process.env.STATIC_PORT": JSON.stringify(process.env.STATIC_PORT)
    }),
    new ExtractTextPlugin("bundle.css"),
    new CopyWebpackPlugin([{ from: "./cb_icons", to: "cb_icons" }]),
    WatchTimePlugin
  ],
  node: { fs: "empty" },
  externals: [{ "./cptable": "var cptable" }, { "./jszip": "jszip" }]
};

module.exports = config;
```

**Comment by sca-** [comment]
Hello Elvira! 🙂 
It's nice to see that somebody is still using this plugin despite that `webpack@4` is showing this info in it's output by default already.
![image](https://user-images.githubusercontent.com/6407411/39322065-5698084e-4991-11e8-902d-40896977e323.png)

Nevertheless, I've tried to catch this bug using `webpack@3` and `webpack@4` but never had success. 
If this issue is still actual for you, please report me NodeJS and Webpack versions you're using.

Regards, 
Evgeniy

**Comment by sca-** [comment]
Couldn't reproduce this issue.
Closing for inactivity.
@ElviraCB please reopen if needed
